// <auto-generated />
using System;
using JuvenilesColon.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JuvenilesColon.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191012193136_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("JuvenilesColon.API.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("JugadorId");

                    b.Property<bool>("Principal");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("JuvenilesColon.API.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Altura");

                    b.Property<string>("Apellido");

                    b.Property<DateTime?>("FechaIngreso");

                    b.Property<DateTime?>("FechaNacimiento");

                    b.Property<string>("Localidad");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("JuvenilesColon.API.Models.Posicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int?>("JugadorId");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("Posicion");
                });

            modelBuilder.Entity("JuvenilesColon.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Gender");

                    b.Property<string>("KnownAs");

                    b.Property<DateTime>("LastActive");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Surname");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JuvenilesColon.API.Models.Foto", b =>
                {
                    b.HasOne("JuvenilesColon.API.Models.Jugador", "Jugador")
                        .WithMany("Fotos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JuvenilesColon.API.Models.Posicion", b =>
                {
                    b.HasOne("JuvenilesColon.API.Models.Jugador")
                        .WithMany("Posiciones")
                        .HasForeignKey("JugadorId");
                });
#pragma warning restore 612, 618
        }
    }
}
